-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
-- Auto-resize ToggleTerm terminals when they open
-- vim.api.nvim_create_autocmd({ "TermOpen", "WinEnter" }, {
--   pattern = "term://*",
--   callback = function()
--     local bufname = vim.api.nvim_buf_get_name(0)
--     if bufname:match("term://") then
--       vim.cmd("resize 15")
--     end
--   end,
-- })
